language: node_js

node_js:
  - "12"
  - "11"
  - "10"
  - "8"

before_script:
  - npm run lint
script:
  - npm run build
after_success:
  - npx semantic-release

notifications:
  email:
    on_success: never
    on_failure: always
